[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
# FIREBASE_API_KEY
# FIREBASE_AUTH_DOMAIN  
# FIREBASE_PROJECT_ID
# FIREBASE_STORAGE_BUCKET
# FIREBASE_MESSAGING_SENDER_ID
# FIREBASE_APP_ID 