[build]
  base = "/"
  command = "cd frontend && npm ci && npm run build"
  functions = "netlify/functions"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.2.3"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 